# Generated by Django 4.2.25 on 2025-10-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_status_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_mode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
