# Generated by Django 4.2.26 on 2025-11-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_remove_product_product_price_gt_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='frecuencia_riego_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sensibilidad_climatica',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ultima_fecha_riego',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vida_util_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlantCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('RIEGO', 'Riego'), ('PODA', 'Poda'), ('CAMBIO_MACETA', 'Cambio de maceta')], max_length=20)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuidados', to='api.product')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RIEGO', 'Riego atrasado'), ('VIDA_UTIL', 'Vida útil excedida'), ('SOBRESTOCK', 'Sobrestock / sin rotación'), ('RIESGO_ALTO', 'Riesgo climático alto')], max_length=20)),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico')], default='ADVERTENCIA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.product')),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'resuelta'], name='idx_alert_tipo_resuelta'), models.Index(fields=['fecha_creacion'], name='idx_alert_fecha')],
            },
        ),
    ]
