# Generated by Django 4.2.26 on 2025-11-19 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_fecha_ingreso_product_frecuencia_riego_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_pct',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento aplicado al precio (0-90).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='plantcare',
            name='tipo_accion',
            field=models.CharField(choices=[('RIEGO', 'Riego'), ('PODA', 'Poda'), ('CAMBIO_MACETA', 'Cambio de maceta'), ('EXTENDER_VIDA', 'Extensión de vida útil')], max_length=20),
        ),
    ]
