# Generated by Django 4.2.26 on 2025-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_discount_pct_alter_plantcare_tipo_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_pct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_base',
            field=models.PositiveIntegerField(default=0, help_text='Precio unitario antes del descuento'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(help_text='Precio unitario al momento de la compra (ya con descuento)'),
        ),
    ]
